flowchart TD
    classDef missing stroke-dasharray: 5
    alembic["alembic\n1.17.2"]
    annotated-types["annotated-types\n0.7.0"]
    antlr4-python3-runtime["antlr4-python3-runtime\n4.13.2"]
    anyio["anyio\n4.12.0"]
    argcomplete["argcomplete\n3.6.3"]
    arrow["arrow\n1.4.0"]
    attrs["attrs\n25.4.0"]
    backoff["backoff\n2.2.1"]
    boolean-py["boolean.py\n5.0"]
    certifi["certifi\n2025.11.12"]
    chardet["chardet\n5.2.0"]
    charset-normalizer["charset-normalizer\n3.4.4"]
    click_0["click\n8.3.1"]
    coloredlogs["coloredlogs\n14.0"]
    colorlog["colorlog\n6.10.1"]
    cyclonedx-bom["cyclonedx-bom\n7.2.1"]
    cyclonedx-python-lib["cyclonedx-python-lib\n11.6.0"]
    dagster-graphql["dagster-graphql\n1.9.11"]
    dagster-pipes["dagster-pipes\n1.9.11"]
    dagster-postgres["dagster-postgres\n0.25.11"]
    dagster-webserver["dagster-webserver\n1.9.11"]
    dagster["dagster\n1.9.11"]
    defusedxml["defusedxml\n0.7.1"]
    dependency-groups["dependency-groups\n1.3.1"]
    distlib["distlib\n0.4.0"]
    dnspython["dnspython\n2.8.0"]
    docker-compose-graph["docker-compose-graph\n1.0.0.post1.dev4+g3b0ba2c26"]
    docstring-parser["docstring_parser\n0.17.0"]
    email-validator["email-validator\n2.3.0"]
    filelock["filelock\n3.20.1"]
    fqdn["fqdn\n1.5.1"]
    fsspec["fsspec\n2025.12.0"]
    gitdb["gitdb\n4.0.12"]
    gitpython["GitPython\n3.1.45"]
    gql["gql\n3.5.3"]
    graphene["graphene\n3.4.3"]
    graphql-core["graphql-core\n3.2.6"]
    graphql-relay["graphql-relay\n3.2.0"]
    graphviz["graphviz\n0.21"]
    greenlet["greenlet\n3.3.0"]
    grpcio-health-checking["grpcio-health-checking\n1.71.2"]
    grpcio["grpcio\n1.76.0"]
    h11["h11\n0.16.0"]
    httptools["httptools\n0.7.1"]
    humanfriendly["humanfriendly\n10.0"]
    humanize["humanize\n4.15.0"]
    idna["idna\n3.11"]
    isoduration["isoduration\n20.11.0"]
    jinja2["Jinja2\n3.1.6"]
    jsonpointer["jsonpointer\n3.0.0"]
    jsonschema-specifications["jsonschema-specifications\n2025.9.1"]
    jsonschema["jsonschema\n4.25.1"]
    lark["lark\n1.3.1"]
    license-expression["license-expression\n30.4.4"]
    lxml["lxml\n6.0.2"]
    mako["Mako\n1.3.10"]
    markdown-it-py["markdown-it-py\n4.0.0"]
    markupsafe["MarkupSafe\n3.0.3"]
    mdurl["mdurl\n0.1.2"]
    multidict["multidict\n6.7.0"]
    nox["nox\n2025.11.12"]
    openstudiolandscapes-template["OpenStudioLandscapes-Template\n0.0.0"]
    openstudiolandscapes["OpenStudioLandscapes\n0.0.0"]
    packageurl-python["packageurl-python\n0.17.6"]
    packaging["packaging\n25.0"]
    pathlib-abc["pathlib_abc\n0.5.2"]
    pip-requirements-parser["pip-requirements-parser\n32.0.1"]
    pip["pip\n25.3"]
    pipdeptree["pipdeptree\n2.30.0"]
    platformdirs["platformdirs\n4.5.1"]
    propcache["propcache\n0.4.1"]
    protobuf["protobuf\n5.29.5"]
    psycopg2-binary["psycopg2-binary\n2.9.11"]
    py-serializable["py-serializable\n2.1.0"]
    pydantic-core["pydantic_core\n2.41.5"]
    pydantic["pydantic\n2.12.5"]
    pydot["pydot\n4.0.1"]
    pygments["Pygments\n2.19.2"]
    pyparsing["pyparsing\n3.3.1"]
    python-dateutil["python-dateutil\n2.9.0.post0"]
    python-dotenv["python-dotenv\n1.2.1"]
    pytz["pytz\n2025.2"]
    pyyaml["PyYAML\n6.0.3"]
    referencing["referencing\n0.37.0"]
    requests-toolbelt["requests-toolbelt\n1.0.0"]
    requests["requests\n2.32.5"]
    rfc3339-validator["rfc3339-validator\n0.1.4"]
    rfc3986-validator["rfc3986-validator\n0.1.1"]
    rfc3987-syntax["rfc3987-syntax\n1.1.0"]
    rich["rich\n14.2.0"]
    rpds-py["rpds-py\n0.30.0"]
    setuptools["setuptools\n80.9.0"]
    six["six\n1.17.0"]
    smmap["smmap\n5.0.2"]
    snakemd["SnakeMD\n2.4.0"]
    sortedcontainers["sortedcontainers\n2.4.0"]
    sqlalchemy["SQLAlchemy\n2.0.45"]
    starlette["starlette\n0.50.0"]
    structlog["structlog\n25.5.0"]
    tabulate["tabulate\n0.9.0"]
    tomli["tomli\n2.3.0"]
    toposort["toposort\n1.10"]
    tqdm["tqdm\n4.67.1"]
    typing-extensions["typing_extensions\n4.15.0"]
    typing-inspection["typing-inspection\n0.4.2"]
    tzdata["tzdata\n2025.3"]
    universal-pathlib["universal_pathlib\n0.3.7"]
    uri-template["uri-template\n1.3.0"]
    urllib3["urllib3\n2.6.2"]
    uvicorn["uvicorn\n0.40.0"]
    uvloop["uvloop\n0.22.1"]
    virtualenv["virtualenv\n20.35.4"]
    watchdog["watchdog\n5.0.3"]
    watchfiles["watchfiles\n1.1.1"]
    webcolors["webcolors\n25.10.0"]
    websockets["websockets\n15.0.1"]
    yarl["yarl\n1.22.0"]
    alembic -- ">=1.4.0" --> sqlalchemy
    alembic -- ">=4.12" --> typing-extensions
    alembic -- "any" --> mako
    anyio -- ">=2.8" --> idna
    anyio -- ">=4.5" --> typing-extensions
    arrow -- ">=2.7.0" --> python-dateutil
    arrow -- "any" --> tzdata
    coloredlogs -- ">=7.1" --> humanfriendly
    cyclonedx-bom -- ">=0.11,<2" --> packageurl-python
    cyclonedx-bom -- ">=22,<26" --> packaging
    cyclonedx-bom -- ">=32.0,<33.0" --> pip-requirements-parser
    cyclonedx-bom -- ">=5.1,<6.0" --> chardet
    cyclonedx-bom -- ">=8.0,<12" --> cyclonedx-python-lib
    cyclonedx-python-lib -- ">=0.11,<2" --> packageurl-python
    cyclonedx-python-lib -- ">=2.1.0,<3.0.0" --> py-serializable
    cyclonedx-python-lib -- ">=2.4.0,<3.0.0" --> sortedcontainers
    cyclonedx-python-lib -- ">=30,<31" --> license-expression
    cyclonedx-python-lib -- ">=4.6,<5.0" --> typing-extensions
    dagster -- "<3" --> tomli
    dagster -- "<5" --> tqdm
    dagster -- "==1.9.11" --> dagster-pipes
    dagster -- ">=0.8.3,<6" --> watchdog
    dagster -- ">=1.0" --> toposort
    dagster -- ">=1.0,<3" --> sqlalchemy
    dagster -- ">=1.2.1,!=1.7.0,!=1.6.3,!=1.11.0" --> alembic
    dagster -- ">=1.44.0" --> grpcio
    dagster -- ">=1.44.0" --> grpcio-health-checking
    dagster -- ">=2,<3.0.0" --> pydantic
    dagster -- ">=20.9" --> packaging
    dagster -- ">=4,<6" --> protobuf
    dagster -- ">=4.10.0,<5" --> typing-extensions
    dagster -- ">=5.0" --> click_0
    dagster -- ">=5.1" --> pyyaml
    dagster -- ">=6.1,<=14.0" --> coloredlogs
    dagster -- "any" --> antlr4-python3-runtime
    dagster -- "any" --> docstring-parser
    dagster -- "any" --> filelock
    dagster -- "any" --> jinja2
    dagster -- "any" --> python-dotenv
    dagster -- "any" --> pytz
    dagster -- "any" --> requests
    dagster -- "any" --> rich
    dagster -- "any" --> setuptools
    dagster -- "any" --> six
    dagster -- "any" --> structlog
    dagster -- "any" --> tabulate
    dagster -- "any" --> universal-pathlib
    dagster-graphql -- "==1.9.11" --> dagster
    dagster-graphql -- ">=3,<4" --> gql
    dagster-graphql -- ">=3,<4" --> graphene
    dagster-graphql -- "any" --> requests
    dagster-graphql -- "any" --> starlette
    dagster-postgres -- "==1.9.11" --> dagster
    dagster-postgres -- "any" --> psycopg2-binary
    dagster-webserver -- "!=0.36.0" --> starlette
    dagster-webserver -- "==1.9.11" --> dagster
    dagster-webserver -- "==1.9.11" --> dagster-graphql
    dagster-webserver -- ">=7.0,<9.0" --> click_0
    dagster-webserver -- "any" --> uvicorn
    dependency-groups -- "any" --> packaging
    docker-compose-graph -- "any" --> graphviz
    docker-compose-graph -- "any" --> jinja2
    docker-compose-graph -- "any" --> pydot
    docker-compose-graph -- "any" --> python-dotenv
    docker-compose-graph -- "any" --> pyyaml
    email-validator -- ">=2.0.0" --> dnspython
    email-validator -- ">=2.0.0" --> idna
    gitdb -- ">=3.0.1,<6" --> smmap
    gitpython -- ">=4.0.1,<5" --> gitdb
    gql -- ">=1.11.1,<3.0" --> backoff
    gql -- ">=1.6,<2.0" --> yarl
    gql -- ">=3.0,<5" --> anyio
    gql -- ">=3.2,<3.2.7" --> graphql-core
    graphene -- ">=2.7.0,<3" --> python-dateutil
    graphene -- ">=3.1,<3.3" --> graphql-core
    graphene -- ">=3.1,<3.3" --> graphql-relay
    graphene -- ">=4.7.1,<5" --> typing-extensions
    graphql-relay -- ">=3.2,<3.3" --> graphql-core
    grpcio -- "~=4.12" --> typing-extensions
    grpcio-health-checking -- ">=1.71.2" --> grpcio
    grpcio-health-checking -- ">=5.26.1,<6.0dev" --> protobuf
    isoduration -- ">=0.15.0" --> arrow
    jinja2 -- ">=2.0" --> markupsafe
    jsonschema -- ">=0.28.4" --> referencing
    jsonschema -- ">=0.7.1" --> rpds-py
    jsonschema -- ">=2023.03.6" --> jsonschema-specifications
    jsonschema -- ">=22.2.0" --> attrs
    jsonschema-specifications -- ">=0.31.0" --> referencing
    license-expression -- ">=4.0" --> boolean-py
    mako -- ">=0.9.2" --> markupsafe
    markdown-it-py -- "~=0.1" --> mdurl
    nox -- ">=1.1" --> dependency-groups
    nox -- ">=1.9.4,<4" --> argcomplete
    nox -- ">=2.6.1,<7" --> colorlog
    nox -- ">=20.15" --> virtualenv
    nox -- ">=21" --> packaging
    nox -- ">=24.1" --> attrs
    nox -- ">=4" --> humanize
    openstudiolandscapes -- "==0.25.11" --> dagster-postgres
    openstudiolandscapes -- "==1.9.11" --> dagster
    openstudiolandscapes -- "==1.9.11" --> dagster-webserver
    openstudiolandscapes -- "any" --> docker-compose-graph
    openstudiolandscapes -- "any" --> email-validator
    openstudiolandscapes -- "any" --> gitpython
    openstudiolandscapes -- "any" --> nox
    openstudiolandscapes -- "any" --> pydot
    openstudiolandscapes -- "any" --> pyyaml
    openstudiolandscapes -- "any" --> snakemd
    openstudiolandscapes-template -- "==1.9.11" --> dagster
    openstudiolandscapes-template -- "any" --> docker-compose-graph
    openstudiolandscapes-template -- "any" --> email-validator
    openstudiolandscapes-template -- "any" --> gitpython
    openstudiolandscapes-template -- "any" --> openstudiolandscapes
    openstudiolandscapes-template -- "any" --> pyyaml
    openstudiolandscapes-template -- "any" --> snakemd
    pip-requirements-parser -- "any" --> packaging
    pip-requirements-parser -- "any" --> pyparsing
    pipdeptree -- ">=25" --> packaging
    pipdeptree -- ">=25.2" --> pip
    py-serializable -- ">=0.7.1,<0.8.0" --> defusedxml
    pydantic -- "==2.41.5" --> pydantic-core
    pydantic -- ">=0.4.2" --> typing-inspection
    pydantic -- ">=0.6.0" --> annotated-types
    pydantic -- ">=4.14.1" --> typing-extensions
    pydantic-core -- ">=4.14.1" --> typing-extensions
    pydot -- ">=3.1.0" --> pyparsing
    python-dateutil -- ">=1.5" --> six
    referencing -- ">=0.7.0" --> rpds-py
    referencing -- ">=22.2.0" --> attrs
    referencing -- ">=4.4.0" --> typing-extensions
    requests -- ">=1.21.1,<3" --> urllib3
    requests -- ">=2,<4" --> charset-normalizer
    requests -- ">=2.5,<4" --> idna
    requests -- ">=2017.4.17" --> certifi
    requests-toolbelt -- ">=2.0.1,<3.0.0" --> requests
    rfc3339-validator -- "any" --> six
    rfc3987-syntax -- ">=1.2.2" --> lark
    rich -- ">=2.13.0,<3.0.0" --> pygments
    rich -- ">=2.2.0" --> markdown-it-py
    sqlalchemy -- ">=1" --> greenlet
    sqlalchemy -- ">=4.6.0" --> typing-extensions
    starlette -- ">=3.6.2,<5" --> anyio
    starlette -- ">=4.10.0" --> typing-extensions
    typing-inspection -- ">=4.12.0" --> typing-extensions
    universal-pathlib -- ">=0.5.1,<0.6.0" --> pathlib-abc
    universal-pathlib -- ">=2024.5.0" --> fsspec
    uvicorn -- ">=0.8" --> h11
    uvicorn -- ">=7.0" --> click_0
    virtualenv -- ">=0.3.7,<1" --> distlib
    virtualenv -- ">=3.12.2,<4" --> filelock
    virtualenv -- ">=3.9.1,<5" --> platformdirs
    watchfiles -- ">=3.0.0" --> anyio
    yarl -- ">=0.2.1" --> propcache
    yarl -- ">=2.0" --> idna
    yarl -- ">=4.0" --> multidict

